# This file should ONLY be uncommented if using wlr desktop portal and experiencing 30fps limit (at screencasting).

#context.properties = {
#    default.clock.quantum = 256
#    default.clock.min-quantum = 256
#    default.clock.max-quantum = 256
#}
