# ────────────────────────
# MONITORS
# ────────────────────────
monitorrule=name:^eDP-1$,width:1920,height:1080,refresh:144,x:0,y:0,scale:1.2
#monitorrule=name:DP-2,width:1920,height:1080,refresh:180,x:0,y:0,scale:1
#monitorrule=name:^eDP-1$,width:1280,height:720,refresh:144,x:0,y:0,scale:1
#monitorrule=name:^eDP-1$,width:1920,height:1080,refresh:144,x:0,y:0,scale:1

# ────────────────────────
# AUTOSTART
# ────────────────────────
exec-once=dbus-update-activation-environment --all
exec-once=qs -c noctalia-shell
exec-once=blueman-applet
exec-once=nm-applet --indicator
#exec-once=systemctl --user import-environment WAYLAND-DISPLAY XDG-CURRENT-DESKTOP

# ────────────────────────
# CUSTOMIZATION
# ────────────────────────
borderpx=3
focuscolor=0x7aa2f7ff
bordercolor=0x24283bff
dropcolor=0x8FBA7C00
border-radius=8
blur=1
#blur-optimized=0
shadows=1
shadows-size=7
shadows-position-x=0
shadows-position-y=0
shadowscolor=0x000000ff
unfocused-opacity=0.8
blur-params-num-passes=3
blur-params-radius=5
windowrule-focused=opacity:0.8,appid:st|foot
layerrule-blur,quickshell

# ────────────────────────
# INPUT
# ────────────────────────
repeat-rate=25
repeat-delay=360
mouse-accel-profile=0

# ────────────────────────
# ANIMATIONS
# ────────────────────────
layer-animations=1
layer-animation-type-open=slide
layer-animation-type-close=zoom
animation-type-close=zoom

# ────────────────────────
# KEYBINDS
# ────────────────────────
# Apps
bind=SUPER,Return,spawn,st
bind=CTRL+ALT,T,spawn,foot
bind=SUPER,E,spawn,pcmanfm
bind=SUPER,R,spawn,rofi -show drun
bind=NONE,Print,spawn-shell,grim -g "$(slurp)" - | wl-copy
# Sound
bind=NONE,XF86AudioRaiseVolume,spawn-shell,wpctl set-volume @DEFAULT-SINK@ "5%+"
bind=NONE,XF86AudioLowerVolume,spawn-shell,wpctl set-volume @DEFAULT-SINK@ "5%-"
bind=NONE,XF86AudioMute,spawn-shell,wpctl set-mute @DEFAULT-SINK@ toggle
# Brightness
bind=NONE,XF86MonBrightnessUp,spawn-shell, brightnessctl set +5%
bind=NONE,XF86MonBrightnessDown,spawn-shell, brightnessctl set 5%-
# Session
bind=ALT,F4,killclient
bind=SUPER+SHIFT,E,quit
bind=SUPER+SHIFT,S,reload-config

# ────────────────────────
# WINDOW MANAGEMENT
# ────────────────────────
bind=SUPER,1,view,1
bind=SUPER,2,view,2
bind=SUPER,3,view,3
bind=SUPER,4,view,4
bind=SUPER,5,view,5
bind=SUPER,6,view,6
bind=SUPER,7,view,7
bind=SUPER,8,view,8
bind=SUPER,9,view,9
bind=SUPER,0,view,10
bind=SUPER+SHIFT,1,tag,1
bind=SUPER+SHIFT,2,tag,2
bind=SUPER+SHIFT,3,tag,3
bind=SUPER+SHIFT,4,tag,4
bind=SUPER+SHIFT,5,tag,5
bind=SUPER+SHIFT,6,tag,6
bind=SUPER+SHIFT,7,tag,7
bind=SUPER+SHIFT,8,tag,8
bind=SUPER+SHIFT,9,tag,9
bind=SUPER+SHIFT,0,tag,10
bind=SUPER,up,focusdir,up
bind=SUPER,down,focusdir,down
bind=SUPER,left,focusdir,left
bind=SUPER,right,focusdir,right
bind=SUPER+SHIFT,Left,exchange-client,left
bind=SUPER+SHIFT,Right,exchange-client,right
bind=SUPER+SHIFT,Up,exchange-client,up
bind=SUPER+SHIFT,Down,exchange-client,down
bind=SUPER,F,togglefullscreen
bind=SUPER,T,togglefloating
bind=SUPER,N,switch-layout
bind=ALT,Tab,focusstack,next
bind=ALT+SHIFT,Tab,focusstack,prev
bind=SUPER,i,minimized
bind=ALT,z,toggle-scratchpad
drag-tile-to-tile=1
new-is-master=0
mousebind=SUPER,btn-left,moveresize,curmove
mousebind=SUPER,btn-right,moveresize,curresize
