# Autostart
monitor=DP-2,1920x1080@180,0x0,1

exec-once=dbus-update-activation-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once=/usr/libexec/xdg-desktop-portal
exec-once=blueman-applet
exec-once=nm-applet --indicator
exec-once=dunst
exec-once=qs -c noctalia-shell
exec-once=gentoo-pipewire-launcher

env=XCURSOR_SIZE,24
env=XCURSOR_THEME,default
env=QT_QPA_PLATFORM,wayland
env=QT_QPA_PLATFORMTHEME,qt6ct
env=GDK_BACKEND,wayland,x11
env=SDL_VIDEODRIVER,wayland
env=CLUTTER_BACKEND,wayland

# Customization
gaps_in=3
gaps_out=5
border_size=3
active_border_color=0x7aa2f7ff
inactive_border_color=0x24283bff
default_layout=T

border_radius=6
focused_opacity=1.0
unfocused_opacity=0.85

blur=1
blur_layer=1
blur_params_num_passes=3
blur_params_radius=5

animations=1
layer_animations=1
animation_type_open=slide
animation_fade_in=1
animation_duration_open=400
animation_curve_open=0.0,0.9,0.57,1.0
animation_duration_move=200
animation_duration_tag=300

# Binds
$mod=Mod4

bind=$mod,Return,exec,alacritty
bind=CTRL+ALT,T,exec,alacritty
bind=$mod,E,exec,pcmanfm
bind=$mod,R,exec,rofi -show drun
bind=,Print,exec,grim -g "$(slurp)" - | wl-copy

bind=$mod,left,focus_direction,l
bind=$mod,right,focus_direction,r
bind=$mod,up,focus_direction,u
bind=$mod,down,focus_direction,d

bind=$mod+Shift,left,move_direction,l
bind=$mod+Shift,right,move_direction,r
bind=$mod+Shift,up,move_direction,u
bind=$mod+Shift,down,move_direction,d

bind=$mod,F,toggle_fullscreen
bind=$mod,T,toggle_floating
bind=$mod,Space,cycle_layout,1

bind=ALT,F4,kill_client
bind=$mod+Shift,E,exit
bind=$mod+Shift,R,reload

bind=$mod,1,view_tag,1
bind=$mod,2,view_tag,2
bind=$mod,3,view_tag,3
bind=$mod,4,view_tag,4
bind=$mod,5,view_tag,5
bind=$mod,6,view_tag,6
bind=$mod,7,view_tag,7
bind=$mod,8,view_tag,8
bind=$mod,9,view_tag,9
bind=$mod,0,view_tag,10

bind=$mod+Shift,1,move_to_tag,1
bind=$mod+Shift,2,move_to_tag,2
bind=$mod+Shift,3,move_to_tag,3
bind=$mod+Shift,4,move_to_tag,4
bind=$mod+Shift,5,move_to_tag,5
bind=$mod+Shift,6,move_to_tag,6
bind=$mod+Shift,7,move_to_tag,7
bind=$mod+Shift,8,move_to_tag,8
bind=$mod+Shift,9,move_to_tag,9
bind=$mod+Shift,0,move_to_tag,10

bind=,XF86AudioRaiseVolume,exec,wpctl set-volume @DEFAULT_SINK@ 5%+
bind=,XF86AudioLowerVolume,exec,wpctl set-volume @DEFAULT_SINK@ 5%-
bind=,XF86AudioMute,exec,wpctl set-mute @DEFAULT_SINK@ toggle
bind=,XF86MonBrightnessUp,exec,brightnessctl set +5%
bind=,XF86MonBrightnessDown,exec,brightnessctl set 5%-
