# ========================
# AUTOSTART
# ========================
monitorrule=name:^eDP-1$,width:1920,height:1080,refresh:144,x:0,y:0,scale:1.0
exec-once=dbus-update-activation-environment --all
exec-once=systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once=qs -c noctalia-shell
exec-once=blueman-applet
exec-once=nm-applet --indicator

# ========================
# CUSTOMIZATION
# ========================
borderpx=3
focuscolor=0x7aa2f7ff
bordercolor=0x24283bff
border_radius=8
blur=1
blur_params_num_passes=3
blur_params_radius=5
layerrule=blur,quickshell

# ========================
# INPUT
# ========================
repeat_rate=25
repeat_delay=360
accel_profile=0

# ========================
# BINDS
# ========================
# Apps
bind=SUPER,Return,spawn,alacritty
bind=CTRL+ALT,T,spawn,alacritty
bind=SUPER,E,spawn,pcmanfm
bind=SUPER,R,spawn,rofi -show drun
bind=NONE,Print,spawn_shell,grim -g "$(slurp)" - | wl-copy
# Sound
bind=NONE,XF86AudioRaiseVolume,spawn_shell,wpctl set-volume @DEFAULT_SINK@ "5%+"
bind=NONE,XF86AudioLowerVolume,spawn_shell,wpctl set-volume @DEFAULT_SINK@ "5%-"
bind=NONE,XF86AudioMute,spawn_shell,wpctl set-mute @DEFAULT_SINK@ toggle
bind=NONE,XF86AudioRaiseVolume,spawn_shell,wpctl set-volume @DEFAULT_SINK@ "5%+"

# ========================
# WINDOW MANAGEMENT
# ========================
bind=SUPER,Left,focusdir,l
bind=SUPER,Right,focusdir,r
bind=SUPER,Up,focusdir,u
bind=SUPER,Down,focusdir,d
bind=SUPER+SHIFT,Left,exchange_client,left
bind=SUPER+SHIFT,Right,exchange_client,right
bind=SUPER+SHIFT,Up,exchange_client,up
bind=SUPER+SHIFT,Down,exchange_client,down
bind=SUPER,F,togglefullscreen
bind=SUPER,T,togglefloating
bind=SUPER,N,switch_layout
bind=ALT,Tab,focusstack,next
bind=ALT+SHIFT,Tab,focusstack,prev
drag_tile_to_tile=1
new_is_master=0

# ========================
# SESSION
# ========================
bind=ALT,F4,killclient
bind=SUPER+SHIFT,E,quit
bind=SUPER+SHIFT,S,reload_config

# ========================
# TAGS
# ========================
bind=SUPER,1,view,1
bind=SUPER,2,view,2
bind=SUPER,3,view,3
bind=SUPER,4,view,4
bind=SUPER,5,view,5
bind=SUPER,6,view,6
bind=SUPER,7,view,7
bind=SUPER,8,view,8
bind=SUPER,9,view,9
bind=SUPER,0,view,10
bind=SUPER+SHIFT,1,tag,1
bind=SUPER+SHIFT,2,tag,2
bind=SUPER+SHIFT,3,tag,3
bind=SUPER+SHIFT,4,tag,4
bind=SUPER+SHIFT,5,tag,5
bind=SUPER+SHIFT,6,tag,6
bind=SUPER+SHIFT,7,tag,7
bind=SUPER+SHIFT,8,tag,8
bind=SUPER+SHIFT,9,tag,9
bind=SUPER+SHIFT,0,tag,10

# ========================
# MOUSE
# ========================
mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize
